// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApsIkNz6KsOBJvD9Nm1R1kJQPmzA2g-OQ',
    appId: '1:582840550120:web:b3f971ba15d608f003ff5d',
    messagingSenderId: '582840550120',
    projectId: 'auth-a488c',
    authDomain: 'auth-a488c.firebaseapp.com',
    storageBucket: 'auth-a488c.appspot.com',
    measurementId: 'G-33FGFD079D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF4O6eJa4sB_K66wkjlTKRtb7gmgAo47Y',
    appId: '1:582840550120:android:cf1bac1f4b8f843703ff5d',
    messagingSenderId: '582840550120',
    projectId: 'auth-a488c',
    storageBucket: 'auth-a488c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQViFN3hqTJELBNoC7_9HaM_6kX2NwGHM',
    appId: '1:582840550120:ios:087663030aecbd2203ff5d',
    messagingSenderId: '582840550120',
    projectId: 'auth-a488c',
    storageBucket: 'auth-a488c.appspot.com',
    iosBundleId: 'com.example.crop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQViFN3hqTJELBNoC7_9HaM_6kX2NwGHM',
    appId: '1:582840550120:ios:087663030aecbd2203ff5d',
    messagingSenderId: '582840550120',
    projectId: 'auth-a488c',
    storageBucket: 'auth-a488c.appspot.com',
    iosBundleId: 'com.example.crop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApsIkNz6KsOBJvD9Nm1R1kJQPmzA2g-OQ',
    appId: '1:582840550120:web:c937779da390a8b303ff5d',
    messagingSenderId: '582840550120',
    projectId: 'auth-a488c',
    authDomain: 'auth-a488c.firebaseapp.com',
    storageBucket: 'auth-a488c.appspot.com',
    measurementId: 'G-1YKM99D2WE',
  );
}
